### ISSUE TITLE
Use Reddit to save data

### ISSUE THREAD

**Issue by paramt** [paramt/MemeAdviser#8]
### Description:
Instead of using `replied.txt` to keep track of submissions that have already been replied to, we can use reddit's save feature. So writing to file would be replaced by saving a post on Reddit, and accessing that list would be something like:

```python
replied = reddit.user.me().saved(limit=None)
```

Furthermore, `subscribed.txt` can be replaced by a text submission in a private subreddit, which can be edited whenever the subscribed list needs to be updated

### Advantages:
- The script can run from tests directly, making CI tests simpler and increasing code coverage at the same time

**Comment by RDIL** [comment]
Sounds like a better addition

**Comment by paramt** [comment]
@Lachcim [I noticed that you decided to move away from using reddit's save feature for duplicate checking](https://github.com/Lachcim/css-irl-bot/commit/f624d41d659ca08737254ab0aecb553a199eaeb4)... any particular reason for that? Was it too unreliable? We were thinking of getting rid of files and using the save feature, so it would be helpful to have your inputs on this

**Comment by Lachcim** [comment]
@paramt I moved away from the save feature because [all listings on reddit are limited to 1000 entries](https://old.reddit.com/r/redditdev/comments/9fbihn/reddit_api_limiting_to_1000_saved_items/), both via the website and the API. In my particular case, I called the saved() function without the `limit` parameter, which caused my bot to go rogue after 100 processed posts and start creating duplicate replies.

In addition to that, I don't think you can control the order in which the saved posts are listed, which gives you no guarantee that your returned list will contain the most recently saved posts.

Finally, saving your processed posts to a text file allows you to distinguish which posts need reprocessing if you decide to add a new feature with retroactive effects.

**Comment by paramt** [comment]
Oh, I see. Thanks for your inputs @Lachcim, we'll probably continue using files then.
